#!/bin/bash
set_shell_colours () {
	# Colors
	NORMAL="[0;39m"
	WARNING="[1;33m" 
	SECTION="[1;33m" 
	NOTICE="[1;33m"  
	OK="[1;32m"      
	BAD="[1;31m"     
	CYAN="[0;36m"
	BLUE="[0;34m"
	BROWN="[0;33m"
	DARKGRAY="[0;30m"
	GRAY="[0;37m"
	GREEN="[1;32m"
	MAGENTA="[1;35m"
	PURPLE="[0;35m"
	RED="[1;31m"
	YELLOW="[1;33m"
	WHITE="[1;37m"
}
set_shell_colours
unset AWS_ACCOUNTS

# get account names - make sure they match cli config profile names!
AWS_ACCOUNTS=( `cat aws_accounts.txt | grep -v ^\# | awk '{print $2}'` ) 

for acct in "${AWS_ACCOUNTS[@]}"
do
bash vpc-monkey $acct
done
# echo "Done!"
